let age = 70;
console.log(age);
let name1 = "Raj";
console.log(name1);
let isActive = true;
console.log(isActive);
let nums = [3, 5, 6];
console.log(nums);
let section = "3m044";
console.log(section);
export {};